name: WebServer Pipeline
run-name: WebServer 
on:
  push: 
    branches: [main]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: "g++ -std=c++17 -Isrc/core/headers -Isrc/controllers/headers main.cpp src/core/implementation/*.cpp src/controllers/implementation/*.cpp -lssl -lcrypto -o webserver"
      - name: Delete
        run: "rm -rf ~/infrastructure ~/src"
      - name: Replace
        run: "mv -f ./* ~"