name: WebServer Pipeline
run-name: WebServer 
on:
  push: 
    branches: [maintenance/folder-restructuring]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: "make build"
      - name: Delete
        run: "rm -rf ~/client ~/webserver"
      - name: Replace
        run: "mv -f ./client ./webserver ~"